FROM golang:latest as builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o app http/main.go

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/__mock__ /app/__mock__
COPY --from=builder /app/app /app
RUN touch .env

EXPOSE 3001
CMD ["/app/app"]