version: '3'

env:
  ENV: local

dotenv: ['.env']

tasks:
  genpb:
    cmds:
      - ./tools/bin/proto-sdk
  grpc:
    cmds:
      - go run gRPC/main.go
  http:
    cmds:
      - go run http/main.go
  